Offchain signatures + updated `@docknetwork/crypto-wasm`, `@docknetwork/crypto-wasm-ts`.
docknetwork/sdk pull request #348
Opened 2023-05-10 13:39 UTC by olegnn

- Offchain signatures module for `BBS`, `BBS+` and `PS` as per https://github.com/docknetwork/dock-substrate/pull/138
- Integrate updated [@docknetwork/crypto-wasm-ts](https://github.com/docknetwork/crypto-wasm-ts/pull/17) and [@docknetwork/crypto-wasm](https://github.com/docknetwork/crypto-wasm/pull/7)

2023-05-17 13:15 UTC, lovesh requested changes

2023-05-17 13:15 UTC, lovesh commented on src/utils/vc/crypto/Bls12381BBSKeyPairDock2023.js
> +  static signerFactory(key) {
For clarify, rename `signerFactory` of parent class as its signature is different from this.

2023-05-18 15:47 UTC, lovesh approved these changes

2023-05-19 09:43 UTC, lovesh submitted a review, later dismissed

2023-05-19 11:51 UTC, lovesh approved these changes

2023-05-25 15:30 UTC, SamHellawell approved these changes

2023-05-25 15:30 UTC, SamHellawell approved these changes

2023-05-25 15:54 UTC, lovesh approved these changes

2023-05-26 12:39 UTC, maycon-mello approved these changes
looks good

2023-05-26 12:40 UTC, merged